MODULE select_kinds
IMPLICIT NONE
! real variables
INTEGER, PARAMETER :: sp = SELECTED_REAL_KIND(p=6 )
INTEGER, PARAMETER :: wp = SELECTED_REAL_KIND(p=13)

! integer variables
INTEGER, PARAMETER :: sb = SELECTED_INT_KIND(r=0 )
INTEGER, PARAMETER :: wb = SELECTED_INT_KIND(r=3 )
INTEGER, PARAMETER :: fb = SELECTED_INT_KIND(r=7 )
INTEGER, PARAMETER :: eb = SELECTED_INT_KIND(r=15)
END MODULE
